### ISSUE TITLE
How to initialize a collapsable element generated dynamically?

### ISSUE THREAD

**Issue by electrotype** [CodyHouse/cd-collapse-changelog#1]
I have some javascript that generates an element that I want to be collapsable. Since the element doesn't exist at first, when the Cody .js is loaded, that doesn't work.

How do you "enable" components created dynamically so they can be collapsable?

By the way, I think I've seen this with some other of your components... In my opinion, you should always provide a way to enable elements that don't already exist when the Cody .js is initially loaded.

Thanks

**Comment by electrotype** [comment]
I just found out, by looking at the code, that `window.Collapse` is actually exposed! So I can dynamically run `new Collapse(myElement)`. It would be nice to have an example in the doc, though.

**Comment by claudia-romano** [comment]
Hi there, we'll make sure to update the info page with an example. Thanks!
