### ISSUE TITLE
Getting  TypeError: Math[timeFunction] is not a function

### ISSUE THREAD

**Issue by pattyok** [CodyHouse/cd-collapse-changelog#2]
When animate is toggled On, I get this error on click. 

I gather this is caused by a missing Utils function. Do I need an extra file to make it work?

![image](https://github.com/user-attachments/assets/3a625e19-9446-4473-b7b1-e4f1428de487)

**Comment by claudia-romano** [comment]
Hi, we just pushed a fix. You can get the updated code here:
https://codyhouse.co/ds/components/app/collapse

Feel free to reopen the issue if you are still having problems. Cheers!
